# FROM mysql:latest

# COPY attendance_db.sql /docker-entrypoint-initdb.d/

# ENV MYSQL_ROOT_PASSWORD=2312
# ENV MYSQL_USER=esd
# ENV MYSQL_PASSWORD=2312
# ENV MYSQL_DATABASE=attendancedb

# EXPOSE 3306