version: "3"
services:
  telesqldb-service:
    image: mysql:latest
    restart: always
    hostname: telesqldb
    volumes:
      - telesqldb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: a
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: telesessiondb
    networks:
      - tele-mysql-net

  amqplistener-service:
    image: amqplistener
    build: ./AMQPListener
    depends_on:
      - telesqldb-service
    environment:
      HOST_NAME: telesqldb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: a
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: telesessiondb
      BOT_TOKEN: 6294207840:AAHzxcCi7HFYCoVsSBMCWLkpcAhvda28krI
    networks:
      - tele-mysql-net
    volumes:
      - telesqldb_data:/var/lib/mysql

  clumsybot-service:
    image: clumsybot
    build: ./ClumsyBot/
    environment:
      HOST_NAME: telesqldb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: a
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: telesessiondb
      BOT_TOKEN: 6294207840:AAHzxcCi7HFYCoVsSBMCWLkpcAhvda28krI
    depends_on:
      - telesqldb-service
    networks:
      - tele-mysql-net
    volumes:
      - telesqldb_data:/var/lib/mysql
networks:
  tele-mysql-net:
    driver: bridge
volumes:
  telesqldb_data:
