# Generated by Django 4.1.7 on 2023-03-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=255)),
                ('eventName', models.CharField(max_length=255)),
                ('eventConfirmed', models.BooleanField()),
                ('eventType', models.CharField(max_length=255)),
                ('eventLocation', models.CharField(max_length=255)),
                ('eventDate', models.DateField()),
                ('eventFromTime', models.DateTimeField()),
                ('eventToTime', models.DateTimeField()),
                ('eventSignUpForm', models.CharField(max_length=255)),
            ],
        ),
    ]
