# Generated by Django 4.1.7 on 2023-03-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventFromTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventToTime',
            field=models.TimeField(),
        ),
    ]
