# Generated by Django 4.1.7 on 2023-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_eventtotime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.CharField(choices=[('S', 'SMU Sports Union'), ('A', 'Arts and Fraternity Club'), ('I', 'Institute of Innovation and Entrepreneurship'), ('M', 'Managerial Committee'), ('O', 'Other')], max_length=255),
        ),
    ]
