# Generated by Django 4.1.7 on 2023-03-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_event_eventtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='clubName',
            new_name='clubId',
        ),
    ]
